language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: true

addons:
  apt:
    packages:
      - parallel
env:
  global:
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="localhost"
    - TYPO3_DATABASE_USERNAME="root"
    - TYPO3_DATABASE_PASSWORD=""
    - EXT_SOLR_VERSION="dev-release-11.0.x"
  matrix:
    - TYPO3_VERSION="^9.5.0"
    - TYPO3_VERSION="^10.4.0"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
  exclude:

before_install:
  - composer self-update
  - composer --version
  - composer global require fabpot/php-cs-fixer

install:
  - Build/Test/bootstrap.sh
script:
  - Build/Test/cibuild.sh
after_script:
  - Build/Test/cleanup.sh

cache:
  directories:
    - $HOME/.composer/cache
