dist: bionic

language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: true

addons:
  apt:
    packages:
      - parallel
env:
  global:
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="localhost"
    - TYPO3_DATABASE_USERNAME="root"
    - TYPO3_DATABASE_PASSWORD=""
    - EXT_SOLR_VERSION="dev-master"
    - PHP_CS_FIXER_VERSION="v3.0.2"
    - XDEBUG_MODE="coverage"
  matrix:
    - TYPO3_VERSION="^10.4"
    - TYPO3_VERSION="10.4.x-dev"

matrix:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="10.4.x-dev"

before_install:
  - composer self-update
  - composer --version

install:
  - Build/Test/bootstrap.sh
script:
  - Build/Test/cibuild.sh
after_script:
  - Build/Test/cleanup.sh

cache:
  directories:
    - $HOME/.composer/cache
