language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: true

addons:
  apt:
    packages:
      - parallel
env:
  global:
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="localhost"
    - TYPO3_DATABASE_USERNAME="root"
    - TYPO3_DATABASE_PASSWORD=""
    - EXT_SOLR_VERSION="dev-release-9.0.x"
  matrix:
    - TYPO3_VERSION="^8.7.0"
    - TYPO3_VERSION="^9.5.0"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
      php: 7.2
    - env: TYPO3_VERSION="dev-master"
      php: 7.1
    - env: TYPO3_VERSION="dev-master"
      php: 7.0
  exclude:
    - php: 7.0
      env: TYPO3_VERSION="^9.5.0"
    - php: 7.1
      env: TYPO3_VERSION="^9.5.0"
    - php: 7.1
      env: TYPO3_VERSION="dev-master"
    - php: 7.0
      env: TYPO3_VERSION="dev-master"

before_install:
  - composer self-update
  - composer --version
  - composer global require fabpot/php-cs-fixer
  - composer global require namelesscoder/typo3-repository-client

install:
  - Build/Test/bootstrap.sh
script:
  - Build/Test/cibuild.sh
after_script:
  - Build/Test/cleanup.sh

cache:
  directories:
    - $HOME/.composer/cache
